# Generated by Django 4.2.6 on 2023-10-12 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('sex', models.CharField(default=None, max_length=1)),
                ('annual_income', models.IntegerField(default=0)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('mobile', models.IntegerField(default=0)),
                ('occupation', models.CharField(default=None, max_length=50)),
                ('DOB', models.DateField(default=None)),
                ('user_name', models.CharField(default=None, max_length=150)),
                ('BVN', models.CharField(default=None, max_length=50)),
                ('National_ID', models.CharField(default=None, max_length=50)),
                ('ID_number', models.CharField(default=None, max_length=50)),
            ],
            options={
                'verbose_name': 'User Information',
                'verbose_name_plural': 'User Informations',
            },
        ),
        migrations.CreateModel(
            name='OtherTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_your_bank', models.CharField(default=None, max_length=150)),
                ('enter_your_account_name', models.CharField(default=None, max_length=150)),
                ('enter_the_destination_account_number', models.IntegerField()),
                ('enter_the_amount_to_be_transferred', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Other bank transfer',
                'verbose_name_plural': 'Other bank transfers',
            },
        ),
        migrations.CreateModel(
            name='PresentLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='India', max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('user_name', models.CharField(default=None, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('user_name', models.CharField(default=None, max_length=150)),
            ],
            options={
                'verbose_name': 'Account detail',
                'verbose_name_plural': 'Account details',
            },
        ),
        migrations.CreateModel(
            name='MoneyTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_your_account_id', models.CharField(default=None, max_length=150)),
                ('enter_the_destination_account_number', models.IntegerField()),
                ('enter_the_amount_to_be_transferred', models.IntegerField()),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inter bank transfer',
                'verbose_name_plural': 'Inter bank transfers',
            },
        ),
    ]
